### ISSUE TITLE
Typo-collection

### ISSUE THREAD

**Issue by cybic** [workwork/handbook#1]
This is a Small Task Collection. Add a task at the top when you find a typo in the handbook/The Game. Tick it and move it down under the unticked ones when you correct the source. Don't close this task before we've weeded through the source thoroughly.
- [x] At meeting room booking "but also the greates time" _greatest_
- [x] Secret back door -> "keep your card working corretly." _correctly_
- [x] Facebook group -> "other usefull information" _useful_
- [x] Help someone in the community -> quest tip -> "not explicitly asked for it" _ask_
- [x] Hang something on the wall -> "Teretorial control." _territorial_
- [x] Initialize Community project -> Involve another person -> rewards "Larger workfroce" _workforce_
- [x] Add a aggregate task to report typos

**Comment by stephan-nordnes-eriksen** [comment]
Most typos fixed. Might still be some sentence structure issues yet to be discovered.
